###     _____                  _____                   _   _       _
###    /  __ \                |  ___|                 | | (_)     | |
###   | /  \/ ___  _ __ ___  | |__ ___ ___  ___ _ __ | |_ _  __ _| |___
###    | |    / _ \| '__/ _ \ |  __/ __/ __|/ _ \ '_ \| __| |/ _` | / __|
###   | \__/\ (_) | | |  __/ | |__\__ \__ \  __/ | | | |_| | (_| | \__ \
###    \____/\___/|_|  \___| \____/___/___/\___|_| |_|\__|_|\__,_|_|___/

## Generic Messages

# Success message. %prefix% - Prefix, %message% - Message
successMessage: '&9%prefix%> &7%message%'

# Error message. %prefix% - Prefix, %message% - Message
errorMessage: '&4%prefix%> &c%message%'

# Permission message. %permission% - permission
permissionMessage: '&4Permission> &cYou do not have permission to do this! (%permission%)'

notAPlayer: '&cYou must be a player to use this command!'

## ClearChat Command

# /clock command message. %player% - Player who cleared the chat
clearChatSuccess: '&6&lChat Cleared by %player%&6&l!'

# /clock command message if the -s (silent) argument is used.
clearChatSuccessSilent: '&6&lChat Cleared!'

## Clock Command

# /clock command prefix
clockPrefix: 'Clock'

# /clock command message. %clock% - time being displayed.
clockSuccess: 'The current time is &e%clock%&7.'

# Use AM/PM when telling the world's time? Default: true
ampm: true










