###     _____                  _____                   _   _       _
###    /  __ \                |  ___|                 | | (_)     | |
###   | /  \/ ___  _ __ ___  | |__ ___ ___  ___ _ __ | |_ _  __ _| |___
###    | |    / _ \| '__/ _ \ |  __/ __/ __|/ _ \ '_ \| __| |/ _` | / __|
###   | \__/\ (_) | | |  __/ | |__\__ \__ \  __/ | | | |_| | (_| | \__ \
###    \____/\___/|_|  \___| \____/___/___/\___|_| |_|\__|_|\__,_|_|___/

## *Generic Messages*

# Success message. %prefix% - Prefix, %message% - Message
successMessage: '&9%prefix%> &7%message%'

# Error message. %prefix% - Prefix, %message% - Message
errorMessage: '&4%prefix%> &c%message%'

# Permission message. %permission% - permission
permissionMessage: '&4Permission> &cYou do not have permission to do this! (%permission%)'

# Message if player-only command is used by the console.
notAPlayer: '&cYou must be a player to use this command!'

# Message if command's target is offline.
targetNotOnline: '&4%target% &cis not online!'

## *ClearChat Command*

# /clock command message. %player% - Player who cleared the chat
clearChatSuccess: '&6&lChat Cleared by %player%&6&l!'

# /clock command message if the -s (silent) argument is used.
clearChatSuccessSilent: '&6&lChat Cleared!'

## *Clock Command*

# /clock command prefix
clockPrefix: 'Clock'

# /clock command message. %clock% - time being displayed.
clockSuccess: 'The current time is &e%clock%&7.'

# Use AM/PM when telling the world's time? Default: true
ampm: true

## *Day Command*

# /day command prefix
dayPrefix: 'Day'

# /day command message
daySuccess: 'Time on &e%world% &7was set to &eDAY&7.'

## *Feed Command*

# /feed command prefix
feedPrefix: 'Feed'

# /feed command message (feeding yourself)
feedSuccess: 'You were feed!'

# /feed command message (feeding other player)
feedSuccessOther: 'You &efeed %target%&7.'

# /feed command message (feed by other player)
feedSuccessOtherTarget: 'You were &efeed &7by &e%player%&7.'

# /feed incorrect usage message
feedIncorrectUsage: 'Incorrect Usage! Use /feed [player]'

## *Fly Command*

# /fly command prefix
flyPrefix: 'Fly'

# /fly command message (enabling your own fly)
flySuccessEnable: 'Your fly was &eenabled&7.'

# /fly command message (disabling your own fly)
flySuccessDisable: 'Your fly was &edisabled&7.'

# /fly command message (enabling other player's fly)
flySuccessOtherEnable: 'You &eenabled %target%''s &7fly.'

# /fly command message (enabled by other player)
flySuccessOtherEnableTarget: 'Your fly was &eenabled &7by &e%player%&7.'

# /fly command message (disabling other player's fly)
flySuccessOtherDisable: 'You &edisabled %target%''s &7fly.'

# /fly command message (disabled by other player)
flySuccessOtherDisableTarget: 'Your fly was &edisabled &7by &e%player%&7.'

# /fly incorrect usage message
flyIncorrectUsage: 'Incorrect Usage! Use /fly [player]'

## *Heal Command*

# /heal command prefix
healPrefix: 'Heal'

# /heal command message (healing yourself)
healSuccess: 'You were healed!'

# /heal command message (healing other player)
healSuccessOther: 'You &ehealed %target%&7.'

# /heal command message (healed by other player)
healSuccessOtherTarget: 'You were &ehealed &7by &e%player%&7.'

# /heal incorrect usage message
healIncorrectUsage: 'Incorrect Usage! Use /heal [player]'

## *Night Command*

# /night command prefix
nightPrefix: 'Night'

# /night command message
nightSuccess: 'Time on &e%world% &7was set to &eNIGHT&7.'

## *Ping Command*

# /ping command prefix
pingPrefix: 'Ping'

# /ping command message.
pingSuccess: 'Your ping is &e%ping%ms&7.'

# /ping command message when checking other player's ping.
pingSuccessOther: '&e%target%&7''s ping is &e%ping%ms&7.'

# /ping incorrect usage message
pingIncorrectUsage: 'Incorrect Usage! Use /ping [player]'

## *Rain Command*

# /rain command prefix
rainPrefix: 'Rain'

# /rain command message
rainSuccess: 'Weather on &e%world% &7was set to &eRAIN&7.'

## *Sun Command*

# /sun command prefix
sunPrefix: 'Sun'

# /sun command message
sunSuccess: 'Weather on &e%world% &7was set to &eSUNNY&7.'

## **Thunder Command*

# /thunder command prefix
thunderPrefix: 'Thunder'

# /thunder command message
thunderSuccess: 'Weather on &e%world% &7was set to &eTHUNDER&7.'















