###     _____                  _____                   _   _       _
###    /  __ \                |  ___|                 | | (_)     | |
###   | /  \/ ___  _ __ ___  | |__ ___ ___  ___ _ __ | |_ _  __ _| |___
###    | |    / _ \| '__/ _ \ |  __/ __/ __|/ _ \ '_ \| __| |/ _` | / __|
###   | \__/\ (_) | | |  __/ | |__\__ \__ \  __/ | | | |_| | (_| | \__ \
###    \____/\___/|_|  \___| \____/___/___/\___|_| |_|\__|_|\__,_|_|___/

## *Generic Messages*

# Success message. %prefix% - Prefix, %message% - Message
successMessage: '&9%prefix%> &7%message%'

# Error message. %prefix% - Prefix, %message% - Message
errorMessage: '&4%prefix%> &c%message%'

# Permission message. %permission% - permission
permissionMessage: '&4Permission> &cYou do not have permission to do this! (%permission%)'

# Message if player-only command is used by the console.
notAPlayer: '&cYou must be a player to use this command!'

# Message if command's target is offline.
targetNotOnline: '&4%target% &cis not online!'

## *ClearChat Command*

# /clock command message. %player% - Player who cleared the chat
clearChatSuccess: '&6&lChat Cleared by %player%&6&l!'

# /clock command message if the -s (silent) argument is used.
clearChatSuccessSilent: '&6&lChat Cleared!'

## *Clock Command*

# /clock command prefix
clockPrefix: 'Clock'

# /clock command message. %clock% - time being displayed.
clockSuccess: 'The current time is &e%clock%&7.'

# Use AM/PM when telling the world's time? Default: true
ampm: true

## *Fly Command*

# /fly command prefix
flyPrefix: 'Fly'

# /fly command message (enabling your own fly)
flySuccessEnable: 'Your fly was &eenabled&7.'

# /fly command message (disabling your own fly)
flySuccessDisable: 'Your fly was &edisabled&7.'

# /fly command message (enabling other player's fly)
flySucessOtherEnable: 'You &eenabled %target%''s &7fly.'

# /fly command message (enabled by other player)
flySucessOtherEnableTarget: 'Your fly was &eenabled &7by &e%player%&7.'

# /fly command message (disabling other player's fly)
flySucessOtherDisable: 'You &edisabled %target%''s &7fly.'

# /fly command message (disabled by other player)
flySucessOtherDisableTarget: 'Your fly was &edisabled &7by &e%player%&7.'

# /fly incorret usage message
flyIncorrectUsage: 'Incorrect Usage! Use /fly [player]'













