###     _____                  _____                   _   _       _
###    /  __ \                |  ___|                 | | (_)     | |
###   | /  \/ ___  _ __ ___  | |__ ___ ___  ___ _ __ | |_ _  __ _| |___
###    | |    / _ \| '__/ _ \ |  __/ __/ __|/ _ \ '_ \| __| |/ _` | / __|
###   | \__/\ (_) | | |  __/ | |__\__ \__ \  __/ | | | |_| | (_| | \__ \
###    \____/\___/|_|  \___| \____/___/___/\___|_| |_|\__|_|\__,_|_|___/

## Generic Messages

# Sucess message. %prefix% - Prefix, %message% - Message
sucessMessage: '&9%prefix%> &7%message%'


## ClearChat Command


## Clock Command

# /clock command prefix
clockPrefix: 'Clock'

# /clock command message. %clock% - time being displayed.
clockSucess: 'The current time is &e%clock%&7.'

# Use AM/PM when telling the world's time? Default: true
ampm: true










