name: CoreEssentials
version: 0.0.1
main: me.luligabi.coreessentials.CoreEssentials
authors: [Luligabi]
website: https://github.com/Luligabi1/CoreEssentials
commands:
    clearchat:
        description: Clears all recent chat. Use the -s argument to hide who executed the command.
        aliases: [cc]
    clock:
        description: Shows the current time on the player's world.
    day:
        description: Sets time to day on the current world.
    feed:
        description: Replenished yours or other player's hunger bar to the maximum capacity.
    fly:
        description: Toggles yours or other player's ability to fly, regardless of gamemode.
    hat:
        description: Sets your helmet as the item on your hand.
    heal:
        description: Replenished yours or other player's hunger bar to the maximum capacity.
    night:
        description: Sets time to ngiht on the current world
    ping:
        description: Get your latency ping in ms.
    rain:
        description: Sets world weather to rain.
    sun:
        description: Sets world weather to sunny.
    thunder:
        description: Sets world weather to thunder.
        aliases: [storm]
    tpall:
        description: Teleports all Players to the user.
    tphere:
        description: Teleports a player to your location.