name: CoreEssentials
version: 0.0.1
main: me.luligabi.coreessentials.CoreEssentials
authors: [Luligabi]
website: https://github.com/Luligabi1/CoreEssentials
commands:
    clearchat:
        aliases: [cc]
        description: Clears all recent chat. Use the -s argument to hide who executed the command.
    clock:
        description: Shows the current time on the player's world.
    day:
        description: Sets time to day on the current world.
    feed:
        description: Replenished yours or other player's hunger bar to the maximum capacity.
    fly:
        description: Toggles yours or other player's ability to fly, regardless of gamemode.
    heal:
        description: Replenished yours or other player's hunger bar to the maximum capacity.
    night:
        description: Sets time to ngiht on the current world
    ping:
        description: Get your latency ping in ms.
    sun:
        description: Sets world weather to sunny.